config/routes.rb
Rails.application.routes.draw do
  resources :store_csvs
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/store_csv.rb
class StoreCsv < ApplicationRecord
  def self.parse file
    CSV.foreach file.path, headers: true do |csv|
      store_csv = StoreCsv.new name: csv['name'], number: csv['number'], date: csv['date'], description: csv['description']
      store_csv.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/store_csvs_controller.rb
class StoreCsvsController < ApplicationController
  before_action :set_store_csv, only: [:update, :destroy]

  def index
    @store_csvs = StoreCsv.all
  end

  def new
    @store_csv = StoreCsv.new
  end

  def create
    if store_csv_params[:file]
      StoreCsv.parse store_csv_params[:file]

      redirect_to store_csvs_path, notice: 'CSV uploaded'
    else
      @store_csv = StoreCsv.new

      flash.now[:alert] = 'Please, upload the file!'

      render 'new'
    end
  end

  def destroy
    @store_csv.destroy
    respond_to do |format|
      format.html { redirect_to store_csvs_url, notice: 'Store csv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_store_csv
      @store_csv = StoreCsv.find(params[:id])
    end

    def store_csv_params
      params.fetch(:store_csv, {}).permit(:file)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTestVisit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.slim
- flash.each do |key, message|
  p class=key = message

app/views/store_csvs/_form.html.slim
= form_for @store_csv do |f|
  - if @store_csv.errors.any?
    #error_explanation
      h2 = "#{pluralize(@store_csv.errors.count, "error")} prohibited this store_csv from being saved:"
      ul
        - @store_csv.errors.full_messages.each do |message|
          li = message

  = f.file_field :file
  br
  br
  .actions = f.submit 'Upload'

app/views/store_csvs/index.html.slim
= link_to 'Back', root_path

br

= link_to 'Upload CSV', new_store_csv_path

h1 Listing CSV Users

table
  thead
    tr
      th
      th
      th

  tbody
    - @store_csvs.each do |store_csv|
      tr
        td = store_csv.name
        td = link_to 'Destroy', store_csv, data: { confirm: 'Are you sure?' }, method: :delete

app/views/store_csvs/new.html.slim
h1 Upload CSV

== render 'form'

br

= link_to 'Back', store_csvs_path

app/views/welcome/index.html.slim
h1 Visit.org Sample Project
p
  | Please complete the items on the checklist.

  span<> = link_to 'This is the CSV to use.', 'test.csv'
= link_to 'CSV Users List', store_csvs_path

h3 Checklist
ol
  li Create model to store CSV data
  li Upload CSV via a form
  li Save CSV records to database
  li Display success/error message
  li Display users in table